apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: filters.filtercontroller.ks.io
spec:
  group: filtercontroller.ks.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                sidecars:
                  type: array
                  items:
                    type: object
                    properties:
                      image:
                        type: string
                      name:
                        type: string
                      priority:
                        type: integer
                        format: int8
                        nullable: true
                      env:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
  scope: Namespaced
  names:
    plural: filters
    singular: filter
    kind: Filter
---
apiVersion: v1
kind: Namespace
metadata:
  name: filter-namespace
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyb3V0ZXJkaTEzMTUudXYuZXM6MzM0NDMiOnsidXNlcm5hbWUiOiJjbG91ZGxhYiIsInBhc3N3b3JkIjoicmVnaXN0cm8iLCJhdXRoIjoiWTJ4dmRXUnNZV0k2Y21WbmFYTjBjbTg9In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2022-03-15T10:02:25Z"
  name: routerdi-registry-creds
  namespace: metrics
  resourceVersion: "2374187"
  uid: 843b9688-48c8-4ad8-84a5-27925519350c
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filter-controller-sa
  namespace: filter-namespace
imagePullSecrets:
  - name: routerdi-registry-creds
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filter-controller-rol
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filter-controller-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole  
  name: filter-controller-rol
subjects:
- kind: ServiceAccount
  namespace: filter-namespace
  name: filter-controller-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filter-controller-deployment
  namespace: filter-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filter-controller
  template:
    metadata:
      labels:
        app: filter-controller
    spec:
      serviceAccountName: filter-controller-sa
      containers:
      - name: filter-controller
        image: routerdi1315.uv.es:33443/sidecar/filter/controller:1.9.2.test
        env:
          - name: ADMISSION_IMAGE
            value: routerdi1315.uv.es:33443/sidecar/filter/admission:1.9.2.test
          - name: FILTER_NAMESPACE
            value: filter-namespace
        ports:
        - containerPort: 8080