apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: filters.k8sidecar.io
spec:
  group: k8sidecar.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                sidecars:
                  type: array
                  items:
                    type: object
                    properties:
                      image:
                        type: string
                      name:
                        type: string
                        nullable: true
                      priority:
                        type: integer
                        format: int8
                        nullable: true
                      env:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                              nullable: true
                            valueFrom:
                              type: object
                              nullable: true
                      volumeMount:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            mountPath:
                              type: string
                            readOnly:
                              type: boolean
                              nullable: true
                volumes:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      persistentVolumeClaim:
                        type: object
                        nullable: true
                        properties:
                          claimName:
                            type: string
                      configMap:
                        type: object
                        nullable: true
                        properties:
                          name:
                            type: string
                      secret:
                        type: object
                        nullable: true
                        properties:
                          secretName:
                            type: string
  scope: Namespaced
  names:
    plural: filters
    singular: filter
    kind: Filter
---
apiVersion: v1
kind: Namespace
metadata:
  name: filter-namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filter-controller-sa
  namespace: filter-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filter-controller-rol
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filter-controller-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: filter-controller-rol
subjects:
- kind: ServiceAccount
  namespace: filter-namespace
  name: filter-controller-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filter-controller-deployment
  namespace: filter-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filter-controller
  template:
    metadata:
      labels:
        app: filter-controller
    spec:
      serviceAccountName: filter-controller-sa
      containers:
      - name: filter-controller
        image: cloudmedialab/filter-controller:1.0.0
        env:
          - name: ADMISSION_IMAGE
            value: cloudmedialab/filter-admission:1.0.0
          - name: FILTER_NAMESPACE
            value: filter-namespace
        ports:
        - containerPort: 8080