apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
  annotations:
    k8sidecar.port: "PORT"
  labels:
    logauth: "sidecar" # inject logging and auth sidecars
    ratelimiter: "sidecar" # inject ratelimiter sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo-container
        image: ealen/echo-server:0.9.2
        env:
        - name: PORT
          value: "80"

---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  selector:
    app: echo
  ports:
  - port: 80
    targetPort: 80
