apiVersion: v1
 kind: ConfigMap
 metadata:
   name: envoy-config
 data:
   envoy.yaml: |
     static_resources:
       listeners:
       - name: local_listener
         address:
           socket_address:
             address: "127.0.0.1"
             port_value: {{ .Env.PPORT }}
         filter_chains:
         - filters:
           - name: envoy.filters.network.http_connection_manager
             typed_config:
               "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
               stat_prefix: ingress_http
               route_config:
                 name: local_route
                 virtual_hosts:
                 - name: backend
                   domains: ["*"]
                   routes:
                   - match:
                       prefix: "/"
                     route:
                       cluster: local_app
               http_filters:
               - name: envoy.filters.http.router
       clusters:
       - name: local_app
         connect_timeout: 0.25s
         type: STATIC
         lb_policy: ROUND_ROBIN
         load_assignment:
           cluster_name: local_app
           endpoints:
           - lb_endpoints:
             - endpoint:
                 address:
                   socket_address:
                     address: 127.0.0.1
                     port_value: {{ .Env.PPORT + 1 }}
---
apiVersion: k8sidecar.io/v1
kind: Filter
metadata:
  name: ratelimiter
spec:
  sidecars:
    - image: "envoyproxy/envoy:v1.18.3"
      name: "envoy"
      volumeMounts:
        - name: envoy-config-volume
          mountPath: /etc/envoy
  volumes:
      - name: envoy-config-volume
        configMap:
          name: envoy-config