apiVersion: k8sidecar.io/v1
kind: Filter
metadata:
  name: logauth
spec:
  sidecars:
    - image: "cloudmedialab/sidecar-logging:1.0.0"
      name: "logging-container"
      priority: 1
    - image: "cloudmedialab/sidecar-authentication:1.0.0"
      name: "auth-container"
      priority: 3
      env:
        - name: AUTH_TOKEN_NAME
          value: AUTH_TOKEN
        - name: AUTH_TOKEN_KEY
          value: "password"