apiVersion: k8sidecar.io/v1
kind: Filter
metadata:
  name: logauth
spec:
  sidecars:
    - image: "routerdi1315.uv.es:33443/sidecar/logging:1.0.0"
      name: "logging-container"
    - image: "routerdi1315.uv.es:33443/sidecar/auth:1.0.0"
      name: "auth-container"
      env:
        - name: AUTH_TOKEN_NAME
          value: AUTH_TOKEN
        - name: AUTH_TOKEN_KEY
          value: "password"