apiVersion: filtercontroller.ks.io/v1
kind: Filter
metadata:
  name: ratelimiter
spec:
  sidecars:
    - image: "routerdi1315.uv.es:33443/sidecar/ratelimiter:1.0.0"
      name: "ratelimiter_container"